name: teste-CI

#trigger
on:
  pull_request:
    branches:
      - main
jobs:
 #declarar etapas , passo a passo do jobs
 run-tests:
    runs-on: ubuntu-latest #maquina virtual
    steps:
      - name: Checkout
        uses: actions/checkout@v2 #nativo do github

      - name: Setup Node.js
        uses: actions/setup-node@v2  #nativo do github
        with:
          node-version: '18'

      - name: Install dependencies  
        run: yarn

      - name: Run tests
        run: yarn test

 run-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: yarn

      - name: Run lint
        run: yarn lint